### PR TITLE
Remove the cache from the provider.

### PR DESCRIPTION
**Pull request by wRAR**
This removes the cache added in #94. It's possible that there are use cases that I don't see (and which aren't covered by tests) where it's used, but it looks like we shouldn't call the provider multiple times for the same request?

### CODE REVIEW

**Comment by Gallaecio** [comment]
I imagine this was necessary before your item building refactoring, where resolution happened at different stages and the same provider could be called multiple times, and it is not needed anymore. But I suspect @BurnzZ might have a better view here (or/and I might be mixing different caches in my mind).

**Comment by BurnzZ** [comment]
This coincides with https://github.com/scrapy-plugins/scrapy-zyte-api/pull/161/ where we still kinda need the cache, albeit replaced with the new one in https://github.com/scrapinghub/scrapy-poet/pull/184.

**Comment by BurnzZ** [comment]
Ahh I think the lines like `self.update_cache(request, {BrowserHtml: html})` aren't needed anymore. Perhaps it's best to have this after https://github.com/scrapy-plugins/scrapy-zyte-api/pull/161/ is merged?

**Comment by wRAR** [comment]
Do we only need the scrapy-poet one then?

**Comment by kmike** [comment]
Is this still valid?

**Comment by wRAR** [comment]
Done in #161

**Pull request closed without merging**
